// routes/apiKeys.js
// 🔑 API Key Management

const express = require('express');
const router = express.Router();
const auth = require('../middleware/auth');
const adminAuth = require('../middleware/adminAuth');
const mongoose = require('mongoose');
const ApiKey = mongoose.model('ApiKey');

// ============================================================
// 📋 GET ALL API KEYS (Admin only - see all keys)
// ============================================================
router.get('/admin', adminAuth, async (req, res) => {
    try {
        const keys = await ApiKey.find()
            .populate('userId', 'name email')
            .sort({ createdAt: -1 });

        res.json({
            success: true,
            data: keys,
            count: keys.length
        });

    } catch (err) {
        console.error('❌ Get all API Keys error:', err);
        res.status(500).json({ 
            success: false, 
            message: err.message 
        });
    }
});

// ============================================================
// 📋 GET MY API KEYS (User - see their own keys)
// ============================================================
router.get('/', auth, async (req, res) => {
    try {
        const keys = await ApiKey.find({ 
            userId: req.user._id 
        })
        .select('-key') // Don't expose the full key
        .sort({ createdAt: -1 });

        res.json({
            success: true,
            data: keys,
            count: keys.length
        });

    } catch (err) {
        console.error('❌ Get user API Keys error:', err);
        res.status(500).json({ 
            success: false, 
            message: err.message 
        });
    }
});

// ============================================================
// 🔑 GET SINGLE API KEY (User - see their own key)
// ============================================================
router.get('/:id', auth, async (req, res) => {
    try {
        const apiKey = await ApiKey.findOne({
            _id: req.params.id,
            userId: req.user._id
        });

        if (!apiKey) {
            return res.status(404).json({
                success: false,
                message: 'API Key not found'
            });
        }

        res.json({
            success: true,
            data: apiKey
        });

    } catch (err) {
        console.error('❌ Get API Key error:', err);
        res.status(500).json({ 
            success: false, 
            message: err.message 
        });
    }
});

// ============================================================
// 🆕 CREATE API KEY (User - create their own key)
// ============================================================
router.post('/', auth, async (req, res) => {
    try {
        const {
            name,
            permissions,
            rateLimit,
            expiresAt,
            ipWhitelist,
            description
        } = req.body;

        if (!name) {
            return res.status(400).json({
                success: false,
                message: 'Name is required'
            });
        }

        // Check if user already has too many keys (max 5)
        const keyCount = await ApiKey.countDocuments({ 
            userId: req.user._id,
            isActive: true 
        });
        
        if (keyCount >= 5) {
            return res.status(400).json({
                success: false,
                message: 'Maximum 5 active API keys allowed per user'
            });
        }

        // Create new API key (key will be auto-generated by pre-save hook)
        const apiKey = new ApiKey({
            userId: req.user._id,
            name: name.trim(),
            permissions: permissions || {
                shipments: { create: true, read: true, update: true, delete: false },
                tracking: { read: true },
                webhooks: { manage: true },
                drivers: { read: true },
                rates: { read: true }
            },
            rateLimit: rateLimit || { 
                requestsPerMinute: 60, 
                requestsPerDay: 10000 
            },
            expiresAt: expiresAt ? new Date(expiresAt) : null,
            ipWhitelist: ipWhitelist || [],
            description: description || '',
            isActive: true
        });

        await apiKey.save();

        // Log creation
        console.log('🔑 API Key created for user:', req.user.email);

        // Return the key (only shown once on creation)
        res.status(201).json({
            success: true,
            data: {
                _id: apiKey._id,
                name: apiKey.name,
                key: apiKey.key, // ⚠️ Show the actual key only on creation
                permissions: apiKey.permissions,
                rateLimit: apiKey.rateLimit,
                isActive: apiKey.isActive,
                expiresAt: apiKey.expiresAt,
                ipWhitelist: apiKey.ipWhitelist,
                description: apiKey.description,
                createdAt: apiKey.createdAt,
                maskedKey: apiKey.maskedKey
            },
            message: '⚠️ Save this API key now. It will not be shown again!'
        });

    } catch (err) {
        console.error('❌ Create API Key error:', err);
        res.status(500).json({ 
            success: false, 
            message: err.message 
        });
    }
});

// ============================================================
// ✏️ UPDATE API KEY (User - update their own key)
// ============================================================
router.put('/:id', auth, async (req, res) => {
    try {
        const { 
            name, 
            permissions, 
            rateLimit, 
            isActive, 
            expiresAt, 
            ipWhitelist, 
            description 
        } = req.body;

        const apiKey = await ApiKey.findOne({
            _id: req.params.id,
            userId: req.user._id
        });

        if (!apiKey) {
            return res.status(404).json({
                success: false,
                message: 'API Key not found'
            });
        }

        // Update fields
        if (name) apiKey.name = name.trim();
        if (permissions) apiKey.permissions = permissions;
        if (rateLimit) apiKey.rateLimit = rateLimit;
        if (isActive !== undefined) apiKey.isActive = isActive;
        if (expiresAt) apiKey.expiresAt = new Date(expiresAt);
        if (ipWhitelist) apiKey.ipWhitelist = ipWhitelist;
        if (description !== undefined) apiKey.description = description;

        apiKey.updatedAt = new Date();
        await apiKey.save();

        res.json({
            success: true,
            data: {
                _id: apiKey._id,
                name: apiKey.name,
                permissions: apiKey.permissions,
                rateLimit: apiKey.rateLimit,
                isActive: apiKey.isActive,
                expiresAt: apiKey.expiresAt,
                ipWhitelist: apiKey.ipWhitelist,
                description: apiKey.description,
                updatedAt: apiKey.updatedAt,
                maskedKey: apiKey.maskedKey
            },
            message: 'API Key updated successfully'
        });

    } catch (err) {
        console.error('❌ Update API Key error:', err);
        res.status(500).json({ 
            success: false, 
            message: err.message 
        });
    }
});

// ============================================================
// 🗑️ DELETE API KEY (User - delete their own key)
// ============================================================
router.delete('/:id', auth, async (req, res) => {
    try {
        const apiKey = await ApiKey.findOneAndDelete({
            _id: req.params.id,
            userId: req.user._id
        });

        if (!apiKey) {
            return res.status(404).json({
                success: false,
                message: 'API Key not found'
            });
        }

        res.json({
            success: true,
            message: 'API Key deleted successfully'
        });

    } catch (err) {
        console.error('❌ Delete API Key error:', err);
        res.status(500).json({ 
            success: false, 
            message: err.message 
        });
    }
});

// ============================================================
// 🔄 REGENERATE API KEY (User - regenerate their own key)
// ============================================================
router.post('/:id/regenerate', auth, async (req, res) => {
    try {
        const crypto = require('crypto');
        
        const apiKey = await ApiKey.findOne({
            _id: req.params.id,
            userId: req.user._id
        });

        if (!apiKey) {
            return res.status(404).json({
                success: false,
                message: 'API Key not found'
            });
        }

        // Generate new key
        const oldKey = apiKey.key;
        apiKey.key = `tam_${crypto.randomBytes(32).toString('hex')}`;
        apiKey.lastUsed = null;
        apiKey.updatedAt = new Date();
        await apiKey.save();

        // Log regeneration
        console.log('🔄 API Key regenerated for user:', req.user.email);

        res.json({
            success: true,
            data: {
                _id: apiKey._id,
                key: apiKey.key, // ⚠️ Show new key only on regeneration
                name: apiKey.name,
                maskedKey: apiKey.maskedKey,
                regeneratedAt: apiKey.updatedAt
            },
            message: '⚠️ API Key regenerated successfully. Save this new key now!'
        });

    } catch (err) {
        console.error('❌ Regenerate API Key error:', err);
        res.status(500).json({ 
            success: false, 
            message: err.message 
        });
    }
});

// ============================================================
// 📊 GET API KEY STATS (User - see their key usage)
// ============================================================
router.get('/:id/stats', auth, async (req, res) => {
    try {
        const apiKey = await ApiKey.findOne({
            _id: req.params.id,
            userId: req.user._id
        });

        if (!apiKey) {
            return res.status(404).json({
                success: false,
                message: 'API Key not found'
            });
        }

        // Get usage stats from logs
        const WebhookLog = mongoose.model('WebhookLog');
        const usageCount = await WebhookLog.countDocuments({
            'payload.apiKeyId': apiKey._id
        });

        res.json({
            success: true,
            data: {
                name: apiKey.name,
                isActive: apiKey.isActive,
                lastUsed: apiKey.lastUsed,
                createdAt: apiKey.createdAt,
                expiresAt: apiKey.expiresAt,
                usageCount: usageCount,
                maskedKey: apiKey.maskedKey
            }
        });

    } catch (err) {
        console.error('❌ Get API Key stats error:', err);
        res.status(500).json({ 
            success: false, 
            message: err.message 
        });
    }
});

// ============================================================
// 👑 ADMIN ROUTES
// ============================================================

// Admin: Get all API keys (already at /admin)
// Admin: Delete any API key
router.delete('/admin/:id', adminAuth, async (req, res) => {
    try {
        const apiKey = await ApiKey.findByIdAndDelete(req.params.id);

        if (!apiKey) {
            return res.status(404).json({
                success: false,
                message: 'API Key not found'
            });
        }

        res.json({
            success: true,
            message: 'API Key deleted by admin'
        });

    } catch (err) {
        console.error('❌ Admin delete API Key error:', err);
        res.status(500).json({ 
            success: false, 
            message: err.message 
        });
    }
});

// Admin: Toggle API key status
router.patch('/admin/:id/toggle', adminAuth, async (req, res) => {
    try {
        const { isActive } = req.body;

        const apiKey = await ApiKey.findById(req.params.id);

        if (!apiKey) {
            return res.status(404).json({
                success: false,
                message: 'API Key not found'
            });
        }

        apiKey.isActive = isActive !== undefined ? isActive : !apiKey.isActive;
        apiKey.updatedAt = new Date();
        await apiKey.save();

        res.json({
            success: true,
            data: apiKey,
            message: `API Key ${apiKey.isActive ? 'activated' : 'deactivated'}`
        });

    } catch (err) {
        console.error('❌ Toggle API Key error:', err);
        res.status(500).json({ 
            success: false, 
            message: err.message 
        });
    }
});

module.exports = router;